repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.8
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Check if all files follow the clippy style
        language: system
        entry: cargo clippy --all-targets --all-features -- -D warnings
        pass_filenames: false
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        language: golang
        types: ["yaml"]
        files: ^\.github/workflows/
        entry: actionlint
        minimum_pre_commit_version: 3.0.0
      - id: actionlint-docker
        name: Lint GitHub Actions workflow files
        description: Runs actionlint Docker image to lint GitHub Actions workflow files
        language: docker_image
        types: ["yaml"]
        files: ^\.github/workflows/
        entry: docker.io/rhysd/actionlint:1.7.7
      - id: actionlint-system
        name: Lint GitHub Actions workflow files
        description: Runs system-installed actionlint to lint GitHub Actions workflow files
        language: system
        types: ["yaml"]
        files: ^\.github/workflows/
        entry: actionlint