[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.9.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
time = { version = "0.3.41", features = ["serde"] }
