name: Pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    
    - name: Install actionlint
      run: |
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        chmod +x actionlint
        sudo mv actionlint /usr/local/bin/
        actionlint --version

    - name: Run pre-commit
      run: pre-commit run --all-files